### ISSUE TITLE
Not working with OBS studio. Put it in as a browser source, does not show.

### ISSUE THREAD

**Issue by JamesonIsNerd** [zhivotnoya/XION-ChaseCam#17]

**Comment by zhivotnoya** [comment]
Sorry for the delay.  Have you gotten it to work yet?  I just tested it on my end and it worked perfectly.  To help me help you, please explain exactly what you did to produce the non-working issue.

For reference, I've included my OBS source settings for this:

![Screenshot 2022-08-07 115315](https://user-images.githubusercontent.com/3652539/183299552-ef866464-5b32-4fff-8d96-daa40c42a3c5.png)

If the issue persists, please create a new issue ticket.  Thank you!
