### ISSUE TITLE
Delay Fixes / Optimization for W3C

### ISSUE THREAD

**Issue by NeoGriever** [zhivotnoya/XION-ChaseCam#22]
Just a little Rebuild of the script itself. Optimized for W3C validation.

Btw. Fixed issue with not-sync-time at all. Just bind it to the system time permanently. Make it update ever 1/10-second.

Removed not needed jquery integration. Removed not needed font load (is not used in the whole code)

Edit-Area in code is now at top.
[optimized.zip](https://github.com/zhivotnoya/XION-ChaseCam/files/12386795/optimized.zip)

**Comment by zhivotnoya** [comment]
I'll incorporate your changes in the next version. THanks!
