### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Jhonnix3** [zhivotnoya/XION-ChaseCam#25]
is there a way to change the timezone to EST and having the correct time show? right now its showing 5more hours than my current
![image](https://github.com/zhivotnoya/XION-ChaseCam/assets/159584309/f429e558-f1a3-45b2-9ad4-2204a638839b)
![image](https://github.com/zhivotnoya/XION-ChaseCam/assets/159584309/3ee98732-b7d1-4b9e-a7ba-e7787775fb9d)

**Comment by zhivotnoya** [comment]
I did set it for UTC (which would be +5 of EST. However, yes you can change it...

line 109 find day=dt.getUTCDate(); change to day=getDate();
line 110 change to month=monthNames[dt.getMonth()];
line 111 change to year=dt.getFullYear();

line 117-119 change to:

var h=dt.getHours().toString();
var m=dt.getMinutes().toString();
var s=dt.getSeconds().toString();

Hope this helps.
