### ISSUE TITLE
 OBS issues

### ISSUE THREAD

**Issue by luizgrenteski** [zhivotnoya/XION-ChaseCam#6]
Hello how are you?
I need some help ... I already changed the logo, the names, it worked, I managed to fix it. But the reason is the following:
- I open HTML in a live program, like OBS or StreamLabs OBS and in HTML in live, it is making an hour more than my country's standard time. (it is GMT-2, where I live is GMT-3).

I need this help, if you help I am very grateful!

**Comment by gam3vidz** [comment]
Hello, so do you have it hosted locally or on a webserver?

**Comment by luizgrenteski** [comment]
Hi, i have hosted locally...

**Comment by gam3vidz** [comment]
alright can you past the path that you used for the browser source image
Example:

C://luizgrenteski/documnets/bodycam/top-right.html

**Comment by luizgrenteski** [comment]
Okay, I'll test it later, thank you very much!

**Comment by zhivotnoya** [comment]
Thank you for helping him.  I don't check my github as often as I should.
